[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "py-mqtt-actor",
]

[tool.uv.sources]
py-mqtt-actor = { workspace = true }
