services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"     # MQTT
      - "8083:8083"     # MQTT over WebSocket
      - "8084:8084"     # MQTT over Secure WebSocket
      - "8883:8883"     # MQTT Secure
      - "18083:18083"   # Dashboard
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
    restart: unless-stopped

  function-based-actor:
    build: .
    container_name: function-based-actor
    depends_on:
      - emqx
    environment:
      - MQTT_BROKER=emqx
      - MQTT_PORT=1883
      - LOG_LEVEL=INFO
    volumes:
      - ./prints:/app/prints
    restart: unless-stopped
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
